### ISSUE TITLE
centos-7 ssh connection times out with more interfaces added

### ISSUE THREAD

**Issue by nusenu** [chef/bento#1032]
The centos-7 box fails to come up / be reachable via SSH when more network interfaces are added.

reproducer:
```
git clone https://github.com/nusenu/ansible-relayor.git
cd ansible-relayor
kitchen create t-exit-6publicIPs-dedicatedExitIP-2instPerIP-centos-7
```
--> fails to create

the relevant part from .kitchen.yml:
```
  - name: t-exit-6publicIPs-dedicatedExitIP-2instPerIP
    driver:
      network:
      - ["private_network", {ip: "192.0.2.10"}]
      - ["private_network", {ip: "198.51.100.10"}]
      - ["private_network", {ip: "198.51.100.11"}]
      - ["private_network", {ip: "198.51.100.12"}]
      - ["private_network", {ip: "198.51.100.13"}]
      - ["private_network", {ip: "198.51.100.14"}]
```
