### ISSUE TITLE
 Vagrant was unable to mount VirtualBox shared folders - OpenSUSE

### ISSUE THREAD

**Issue by Gsantomaggio** [chef/bento#1185]
# Version:

```
➜ vboxmanage --version
6.0.4r128413
➜  leap_bento vagrant version
Installed Version: 2.2.4
Latest Version: 2.2.4


chef --version
Chef Development Kit Version: 3.8.14
chef-client version: 14.10.9
delivery version: master (9d07501a3b347cc687c902319d23dc32dd5fa621)
berks version: 7.0.7
kitchen version: 1.24.0
inspec version: 3.6.6

```

# Environment: 
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```
# Scenario:

Tryin to use it inside a receipe

# Steps to Reproduce:
Tryin to use it inside a receipe:

```
driver:
  name: <%= ENV['KI_DRIVER'] || 'vagrant' %>

verifier:
  name: inspec

provisioner:
  name: chef_zero
  product_name: chef
  install_strategy: always

transport:
  name: "ssh"

platforms:
  - name: opensuse-leap-15.0

 - name: rabbitmq-erlang-latest-rpm-suse
        includes: ["opensuse-leap-15.0"]
```

# Expected Result:

The opensuse leap 15 running machine

# Actual Result:
```
STDERR: Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 tmp_omnibus_cache /tmp/omnibus/cache
```

I tried other platforms, and it works without problems.
Thank you
