### ISSUE TITLE
Fedora 30 vmware-tools installation fails

### ISSUE THREAD

**Issue by tas50** [chef/bento#1240]
This alert just goes on forever
```
    vmware-iso: What is the directory that contains the init directories (rc0.d/ to
    vmware-iso: rc6.d/)?
    vmware-iso: INPUT: []  default
    vmware-iso:
    vmware-iso: The path "" is not an existing directory.
```
