### ISSUE TITLE
vmware tools won't install on opensuse

### ISSUE THREAD

**Issue by tas50** [chef/bento#1258]
vmware tools are just stuck in an install loop. I know we had similar issues on the RHEL side that we solved before

```
 vmware-iso: What is the directory that contains the init directories (rc0.d/ to
    vmware-iso: rc6.d/)?
    vmware-iso: INPUT: []  default
    vmware-iso:
    vmware-iso: The path "" is not an existing directory.
    vmware-iso:
    vmware-iso: What is the directory that contains the init directories (rc0.d/ to
    vmware-iso: rc6.d/)?
    vmware-iso: INPUT: []  default
    vmware-iso:
    vmware-iso: The path "" is not an existing directory.
    vmware-iso:
    vmware-iso: What is the directory that contains the init directories (rc0.d/ to
    vmware-iso: rc6.d/)?
    vmware-iso: INPUT: []  default
    vmware-iso:
    vmware-iso: The path "" is not an existing directory.
    vmware-iso:
    vmware-iso: What is the directory that contains the init directories (rc0.d/ to
    vmware-iso: rc6.d/)?
    vmware-iso: INPUT: []  default
    vmware-iso:
    vmware-iso: The path "" is not an existing directory.
    vmware-iso:
```
