### ISSUE TITLE
CentOS 7.2 v 2.3.0 does not create

### ISSUE THREAD

**Issue by raycrawford** [chef/bento#679]
Using ChefDK/KitchenCI/Vagrant/VirtualBox, the 2.3.0 version of the CentOS 7.2 image fails when Vagrant tries to connect to the VM via SSH.  Pinning the 2.2.9 version resolves issue.  Not clear why.  Working .kitchen.yml is attached.

```
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

# To make Windows work, need to install vagrant windows plugin, first
# vagrant plugin install vagrant-winrm
# See: https://github.com/criteo/vagrant-winrm

platforms: 
  - name: centos-6.8
    driver:
      network:
        - ['private_network', {ip: '192.168.56.12'}]
    transport:
      name: ssh
      username: vagrant
      password: vagrant
    driver:
      box: bento/centos-6.8
      box_url: https://atlas.hashicorp.com/bento/boxes/centos-6.8/versions/2.2.9/providers/virtualbox.box
  - name: centos-7.2
    driver:
      network:
        - ['private_network', {ip: '192.168.56.13'}]
    transport:
      name: ssh
      username: vagrant
      password: vagrant
    driver:
      box: bento/centos-7.2
      box_url: https://atlas.hashicorp.com/bento/boxes/centos-7.2/versions/2.2.9/providers/virtualbox.box
  - name: mwrock/Windows2012R2
    os_type: windows
    shell_type: powershell
    communicator: winrm
    transport:
      name: winrm
      username: vagrant
      password: vagrant
    driver:
      box: mwrock/Windows2012R2
      box_url: https://atlas.hashicorp.com/mwrock/boxes/Windows2012R2
      network:
        - ['private_network', {ip: '192.168.56.14'}]

suites:
  - name: default
    run_list:
      - recipe[my_httpd::default]
    attributes:
    driver:
        memory: 1024
        cpus: 1
```
