### ISSUE TITLE
Fedora 25/vbox missing?

### ISSUE THREAD

**Issue by flaccid** [chef/bento#749]
https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-25_chef-provisionerless.box - key does not exist.

In `.kitchen.yml`:
```
platforms:
  - name: fedora-25
```
Or, I'm doing something wrong?

**Comment by flaccid** [comment]
Additionally, noticed 404 also for https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-8.6_chef-provisionerless.box (`debian-86`).

**Comment by flaccid** [comment]
Additionally, noticed 404 also for https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.3_chef-provisionerless.box (`centos-73`).

**Comment by flaccid** [comment]
This is what I have to settle with for now:
```
platforms:
  # debian 8.6 box missing
  # - name: debian-8.6
  - name: debian-8.5
  - name: debian-7.11
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  # centos 7.3 box missing
  # - name: centos-7.3
  - name: centos-7.2
  - name: centos-6.8
  # fedora 25 box missing
  # - name: fedora-25
  - name: fedora-24
  # freebsd 11.0 box missing
  # - name: freebsd-11.0
  - name: freebsd-10.3
  - name: opensuse-13.2
```
