### ISSUE TITLE
bento/ubuntu-16.04 has no /usr/bin/python since v2.3.8

### ISSUE THREAD

**Issue by martinfischer** [chef/bento#872]
The bento/ubuntu-16.04 Vagrant box for virtualbox on https://app.vagrantup.com/bento/boxes/ubuntu-16.04 has no python (2) installed since v2.3.8. Ansible provisioning will therefore fail as it needs /usr/bin/python.

python3 is there. 

/usr/bin/python was still there in v2.3.7 and before. LTS should have /usr/bin/python, right?

**Comment by rickard-von-essen** [comment]
Python is not part of the default install of Ubuntu 16.04. You have to install it. See https://www.digitalocean.com/community/tutorials/what-s-new-in-ubuntu-16-04

**Comment by tersmitten** [comment]
This is how we bootstrap 16.04 machines 

```
---
- hosts: ubuntu-1604
  gather_facts: no
  pre_tasks:
    # Needed because python is not installed
    - name: install python (if needed)
      raw: test -e /usr/bin/python || (apt update -y && apt install -y python-minimal)
      register: _python_minimal
      changed_when: _python_minimal.stdout_lines | length > 0

- hosts: all
  roles: [] 
```
